language: java
jdk: oraclejdk8

sudo: required
script: mvn clean verify

services:
  - docker

before_install:
- docker build -t dgreenshtein/yelp-insights .

after_success:
  - bash <(curl -s https://codecov.io/bash)